### ISSUE TITLE
php refresh_db.php Fatal error

### ISSUE THREAD

**Issue by uparrows** [naiymu/konnichiwa#1]
PHP Fatal error:  Class 'mysqli' not found in /volume2/web/konnichiwa-master/scripts/add.php on line 5

**Comment by uparrows** [comment]
php version 7.0
![0](https://user-images.githubusercontent.com/38988286/84143979-11427c00-aa8a-11ea-902d-ec1e00063a4a.JPG)
![1](https://user-images.githubusercontent.com/38988286/84143981-1273a900-aa8a-11ea-80d5-fbe34b740d87.JPG)

**Comment by naiymu** [comment]
I think you just need to install mysqli. You can try [this](https://www.php.net/manual/en/mysqli.installation.php). I should probably add this as one of the requirements.

**Comment by naiymu** [comment]
If you're on ubuntu, you can try [this](https://askubuntu.com/a/773897) askubuntu answer. Check the comments on that answer and the [chat](https://chat.stackexchange.com/rooms/40009/discussion-between-user30424-and-oerdnj) as well if it doesn't fix your problem.

**Comment by naiymu** [comment]
@dezhaoma If you are able to fix your issue, please do let me know, or if you need more help.

**Comment by uparrows** [comment]
> @dezhaoma If you are able to fix your issue, please do let me know, or if you need more help.

thanks , actually i've installed it on my synology nas , which do not contain mysqli , i've also installed appache 2.4 、php7.0 、phpadmin 、web station 、mariadb5 on my nas ; synology package center does not contain mysqli , there is mariadb only ,maybe i should build a docker image for my nas , and it works well on my ubuntu server .

**Comment by naiymu** [comment]
That's good. So I think I'll be closing this issue then.
