### ISSUE TITLE
No directory starting with 'spcl' & Images won't download

### ISSUE THREAD

**Issue by saintly2k** [naiymu/konnichiwa#2]
Okay, I've followed your setup 1:1 and it already looks pretty dope, +rep!
However, I now get those two errors:
No directory starting with 'spcl'
and the other error is, that the images won't download, no matter what.
After I downloaded a Hentai via get.php, it creates a directory into /images/ but doesn't place any images in there. What could trigger this? However, they still show up on the site, just without images.
And I think the "spcl" error may comes from not having any manga yet?
I don't know... I'd be grateful for just any kind of support.
Thanks

**Comment by naiymu** [comment]
>No directory starting with 'spcl'

This just means that you don't have any directory starting with a non-alphabetic character. If you want to change the homepage to show directories starting with an alphabet, say 'A', change the value of `$letter` in `index.php` to `"A"` on line 19. It's `"spcl"` by default.

As for the images not downloading, it seems like a network issue. Maybe try changing your DNS server and see if the images download.

Further questions welcome!

**Comment by naiymu** [comment]
Also, for the image downloading, post the server error logs right after downloading something. Might not be a network issue at all.
